// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqWIj2Aw2oVjQX2GZbS7ttP0Xqm_9o8Q',
    appId: '1:278228907252:web:284f691a506e25ec381aa1',
    messagingSenderId: '278228907252',
    projectId: 'girlride-1',
    authDomain: 'girlride-1.firebaseapp.com',
    databaseURL: 'https://girlride-1-default-rtdb.firebaseio.com',
    storageBucket: 'girlride-1.firebasestorage.app',
    measurementId: 'G-P7VY8D7DKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyYfrw-fdBkTysN6REgyGYflNNNN2um2U',
    appId: '1:278228907252:android:72719cec16349c53381aa1',
    messagingSenderId: '278228907252',
    projectId: 'girlride-1',
    databaseURL: 'https://girlride-1-default-rtdb.firebaseio.com',
    storageBucket: 'girlride-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWoRapnRhyB8Gp1Tgo67I39F8c0_jtzU',
    appId: '1:278228907252:ios:4ae5ebbade329e0f381aa1',
    messagingSenderId: '278228907252',
    projectId: 'girlride-1',
    databaseURL: 'https://girlride-1-default-rtdb.firebaseio.com',
    storageBucket: 'girlride-1.firebasestorage.app',
    iosBundleId: 'com.ttweb.girlride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWoRapnRhyB8Gp1Tgo67I39F8c0_jtzU',
    appId: '1:278228907252:ios:4ae5ebbade329e0f381aa1',
    messagingSenderId: '278228907252',
    projectId: 'girlride-1',
    databaseURL: 'https://girlride-1-default-rtdb.firebaseio.com',
    storageBucket: 'girlride-1.firebasestorage.app',
    iosBundleId: 'com.ttweb.girlride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYqWIj2Aw2oVjQX2GZbS7ttP0Xqm_9o8Q',
    appId: '1:278228907252:web:8adb951bc3c27390381aa1',
    messagingSenderId: '278228907252',
    projectId: 'girlride-1',
    authDomain: 'girlride-1.firebaseapp.com',
    databaseURL: 'https://girlride-1-default-rtdb.firebaseio.com',
    storageBucket: 'girlride-1.firebasestorage.app',
    measurementId: 'G-8ELCYXEJSV',
  );
}
